const openCookieSettings = () => window.dispatchEvent(new Event('agm:open-cookie-settings'));

const socialIcons = {
  instagram: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" strokeWidth="1.8"/><circle cx="12" cy="12" r="4" strokeWidth="1.8"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>,
  youtube: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M21 8.1a3 3 0 0 0-2.1-2.12C17.05 5.5 12 5.5 12 5.5s-5.05 0-6.9.48A3 3 0 0 0 3 8.1 31 31 0 0 0 2.5 12 31 31 0 0 0 3 15.9a3 3 0 0 0 2.1 2.12c1.85.48 6.9.48 6.9.48s5.05 0 6.9-.48A3 3 0 0 0 21 15.9a31 31 0 0 0 .5-3.9 31 31 0 0 0-.5-3.9Z" strokeWidth="1.7"/><path d="m10 9 5 3-5 3V9Z" fill="currentColor" stroke="none"/></svg>,
  discord: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M8.2 7.2a10.4 10.4 0 0 1 7.6 0M7 18.2c3.3 1.5 6.7 1.5 10 0M8.5 5.2 6.7 5.8C4.9 8.5 4 11.4 4.1 15c1.2 1.4 2.5 2.3 4 3l1-1.4M15.5 5.2l1.8.6c1.8 2.7 2.7 5.6 2.6 9.2-1.2 1.4-2.5 2.3-4 3l-1-1.4" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><circle cx="9" cy="12.2" r="1.2" fill="currentColor" stroke="none"/><circle cx="15" cy="12.2" r="1.2" fill="currentColor" stroke="none"/></svg>,
  twitter: <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18.9 2H22l-6.77 7.74L23.2 22h-6.24l-4.89-6.39L6.48 22H3.36l7.25-8.29L2.96 2H9.36l4.42 5.84L18.9 2Zm-1.1 17.84h1.73L8.42 4.05H6.57L17.8 19.84Z"/></svg>,
  email: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3" strokeWidth="1.8"/><path d="m5 8 7 5 7-5" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>,
};

const SoonIcon = ({ name, icon }) => <span title={`${name} coming soon`} aria-label={`${name} coming soon`} className="group relative grid h-11 w-11 cursor-default place-items-center rounded-full border border-zinc-700 text-zinc-400 transition hover:border-zinc-500 hover:text-white"><span className="h-5 w-5">{socialIcons[icon]}</span><span className="pointer-events-none absolute -top-8 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-md bg-white px-2 py-1 text-[9px] font-black uppercase tracking-wider text-zinc-950 shadow-lg group-hover:block">Coming soon</span></span>;

export default function SiteFooter() {
  return <footer className="border-t border-zinc-200 bg-zinc-950 px-5 py-12 text-zinc-300 sm:px-8 sm:py-14">
    <div className="mx-auto grid max-w-[1200px] gap-10 sm:grid-cols-2 lg:grid-cols-[1.7fr_1fr_1fr]">
      <div>
        <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-yellow-300 text-[11px] font-black text-zinc-950">AGM</span><p className="text-base font-black tracking-wide text-white sm:text-lg">ALLGAMERS<span className="text-yellow-300">MARKET</span></p></div>
        <p className="mt-5 max-w-md text-sm leading-7 text-zinc-400">A curated marketplace for permitted digital gaming products and services. AllGamersMarket is independent and is not sponsored or endorsed by game publishers.</p>
        <span title="Discord link coming soon" className="mt-6 inline-flex h-12 items-center gap-3 rounded-xl bg-[#5865f2] px-5 text-sm font-black text-white shadow-lg shadow-[#5865f2]/15"><span className="h-5 w-5">{socialIcons.discord}</span><span>Join our Discord</span><span className="rounded-full bg-white/15 px-2 py-0.5 text-[9px] uppercase tracking-wider">Soon</span></span>
        <div className="mt-5 flex items-center gap-3" aria-label="Social and contact links"><SoonIcon name="Instagram" icon="instagram"/><SoonIcon name="YouTube" icon="youtube"/><SoonIcon name="X / Twitter" icon="twitter"/><a href="mailto:support@allgamersmarket.com" title="Email support@allgamersmarket.com" aria-label="Email support@allgamersmarket.com" className="grid h-11 w-11 place-items-center rounded-full border border-zinc-700 text-zinc-400 transition hover:border-yellow-300 hover:bg-yellow-300 hover:text-zinc-950"><span className="h-5 w-5">{socialIcons.email}</span></a></div>
        <p className="mt-4 text-sm text-zinc-400">Email: <a href="mailto:support@allgamersmarket.com" className="font-semibold text-zinc-200 transition hover:text-yellow-300">support@allgamersmarket.com</a></p>
      </div>
      <nav className="flex flex-col items-start gap-3 text-sm" aria-label="Legal policies"><p className="mb-1 text-xs font-black uppercase tracking-[0.16em] text-white">Policies</p><a href="/terms" className="transition hover:text-white">Terms of Service</a><a href="/privacy" className="transition hover:text-white">Privacy Policy</a><a href="/cookies" className="transition hover:text-white">Cookie Policy</a><a href="/refund-policy" className="transition hover:text-white">Refund Policy</a><a href="/marketplace-rules" className="transition hover:text-white">Marketplace Rules</a><a href="/account-transfer-risks" className="transition hover:text-white">Transfer Risks</a></nav>
      <nav className="flex flex-col items-start gap-3 text-sm" aria-label="Help and resources"><p className="mb-1 text-xs font-black uppercase tracking-[0.16em] text-white">Help & resources</p><a href="/support" className="transition hover:text-white">Support</a><a href="/faq" className="transition hover:text-white">FAQ</a><a href="/blog" className="transition hover:text-white">Blog</a><button type="button" onClick={openCookieSettings} className="transition hover:text-white">Cookie settings</button></nav>
    </div>
    <div className="mx-auto mt-10 flex max-w-[1200px] flex-col gap-1 border-t border-zinc-800 pt-6 text-xs leading-6 text-zinc-500 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} AllGamersMarket. All rights reserved.</span><span>Third-party game names and marks belong to their respective owners.</span></div>
  </footer>;
}
