import { Link } from 'react-router-dom';

const openCookieSettings = () => window.dispatchEvent(new Event('agm:open-cookie-settings'));

const socialIcons = {
  instagram: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" strokeWidth="1.8"/><circle cx="12" cy="12" r="4" strokeWidth="1.8"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>,
  youtube: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M21 8.1a3 3 0 0 0-2.1-2.12C17.05 5.5 12 5.5 12 5.5s-5.05 0-6.9.48A3 3 0 0 0 3 8.1 31 31 0 0 0 2.5 12 31 31 0 0 0 3 15.9a3 3 0 0 0 2.1 2.12c1.85.48 6.9.48 6.9.48s5.05 0 6.9-.48A3 3 0 0 0 21 15.9a31 31 0 0 0 .5-3.9 31 31 0 0 0-.5-3.9Z" strokeWidth="1.7"/><path d="m10 9 5 3-5 3V9Z" fill="currentColor" stroke="none"/></svg>,
  discord: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M8.2 7.2a10.4 10.4 0 0 1 7.6 0M7 18.2c3.3 1.5 6.7 1.5 10 0M8.5 5.2 6.7 5.8C4.9 8.5 4 11.4 4.1 15c1.2 1.4 2.5 2.3 4 3l1-1.4M15.5 5.2l1.8.6c1.8 2.7 2.7 5.6 2.6 9.2-1.2 1.4-2.5 2.3-4 3l-1-1.4" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/><circle cx="9" cy="12.2" r="1.2" fill="currentColor" stroke="none"/><circle cx="15" cy="12.2" r="1.2" fill="currentColor" stroke="none"/></svg>,
  email: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3" strokeWidth="1.8"/><path d="m5 8 7 5 7-5" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>,
};

const SoonIcon = ({ name, icon }) => <span title={`${name} coming soon`} aria-label={`${name} coming soon`} className="group relative grid h-11 w-11 cursor-default place-items-center rounded-full border border-zinc-700 text-zinc-400 transition hover:border-zinc-500 hover:text-white"><span className="h-5 w-5">{socialIcons[icon]}</span><span className="pointer-events-none absolute -top-8 left-1/2 hidden -translate-x-1/2 whitespace-nowrap rounded-md bg-white px-2 py-1 text-[9px] font-black uppercase tracking-wider text-zinc-950 shadow-lg group-hover:block">Coming soon</span></span>;

export default function SiteFooter() {
  return <footer className="border-t border-zinc-200 bg-zinc-950 px-5 py-12 text-zinc-300 sm:px-8 sm:py-14">
    <div className="mx-auto grid max-w-[1200px] gap-10 sm:grid-cols-2 lg:grid-cols-[1.7fr_1fr_1fr]">
      <div><p className="text-base font-black tracking-wide text-white sm:text-lg">ALLGAMERS<span className="text-yellow-300">MARKET</span></p><p className="mt-4 max-w-md text-sm leading-7 text-zinc-400">Independent marketplace. Not endorsed by or affiliated with any game publisher. Only publisher-authorized and lawfully transferable products may be listed.</p><div className="mt-6 flex items-center gap-3" aria-label="Social and contact links"><SoonIcon name="Instagram" icon="instagram"/><SoonIcon name="YouTube" icon="youtube"/><SoonIcon name="Discord" icon="discord"/><Link to="/support" title="Contact support" aria-label="Contact support" className="grid h-11 w-11 place-items-center rounded-full border border-zinc-700 text-zinc-400 transition hover:border-yellow-300 hover:bg-yellow-300 hover:text-zinc-950"><span className="h-5 w-5">{socialIcons.email}</span></Link></div></div>
      <nav className="flex flex-col items-start gap-3 text-sm" aria-label="Legal policies"><p className="mb-1 text-xs font-black uppercase tracking-[0.16em] text-white">Policies</p><Link to="/terms" className="transition hover:text-white">Terms of Service</Link><Link to="/privacy" className="transition hover:text-white">Privacy Policy</Link><Link to="/cookies" className="transition hover:text-white">Cookie Policy</Link><Link to="/refund-policy" className="transition hover:text-white">Refund Policy</Link><Link to="/marketplace-rules" className="transition hover:text-white">Marketplace Rules</Link><Link to="/account-transfer-risks" className="transition hover:text-white">Transfer Risks</Link></nav>
      <nav className="flex flex-col items-start gap-3 text-sm" aria-label="Help and resources"><p className="mb-1 text-xs font-black uppercase tracking-[0.16em] text-white">Help & resources</p><Link to="/support" className="transition hover:text-white">Support</Link><Link to="/faq" className="transition hover:text-white">FAQ</Link><Link to="/blog" className="transition hover:text-white">Blog</Link><button type="button" onClick={openCookieSettings} className="transition hover:text-white">Cookie settings</button></nav>
    </div>
    <div className="mx-auto mt-10 max-w-[1200px] border-t border-zinc-800 pt-6 text-xs leading-6 text-zinc-500">© {new Date().getFullYear()} AllGamersMarket. All third-party names and marks belong to their respective owners.</div>
  </footer>;
}
